version: "3.9"

services:

  redis:
    container_name: redis_myproject
    image: redis/redis-stack:latest
    profiles:
      - redis
    ports:
      - ${REDIS_PORT:-6379}:6379
      - ${REDISINSIGHT_PORT:-8001}:8001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
